// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package yapscan

import (
	procIO "github.com/fkie-cad/yapscan/procIO"
	mock "github.com/stretchr/testify/mock"
)

// mockMemoryReaderFactory is an autogenerated mock type for the memoryReaderFactory type
type mockMemoryReaderFactory struct {
	mock.Mock
}

// NewMemoryReader provides a mock function with given fields: proc, seg
func (_m *mockMemoryReaderFactory) NewMemoryReader(proc procIO.Process, seg *procIO.MemorySegmentInfo) (procIO.MemoryReader, error) {
	ret := _m.Called(proc, seg)

	var r0 procIO.MemoryReader
	if rf, ok := ret.Get(0).(func(procIO.Process, *procIO.MemorySegmentInfo) procIO.MemoryReader); ok {
		r0 = rf(proc, seg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(procIO.MemoryReader)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(procIO.Process, *procIO.MemorySegmentInfo) error); ok {
		r1 = rf(proc, seg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
