// Code generated by mockery v2.14.0. DO NOT EDIT.

package yapscan

import (
	yara "github.com/hillu/go-yara/v4"
	mock "github.com/stretchr/testify/mock"
)

// MockMemoryScanner is an autogenerated mock type for the MemoryScanner type
type MockMemoryScanner struct {
	mock.Mock
}

// ScanMem provides a mock function with given fields: buf
func (_m *MockMemoryScanner) ScanMem(buf []byte) ([]yara.MatchRule, error) {
	ret := _m.Called(buf)

	var r0 []yara.MatchRule
	if rf, ok := ret.Get(0).(func([]byte) []yara.MatchRule); ok {
		r0 = rf(buf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]yara.MatchRule)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(buf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockMemoryScanner interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMemoryScanner creates a new instance of MockMemoryScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMemoryScanner(t mockConstructorTestingTNewMockMemoryScanner) *MockMemoryScanner {
	mock := &MockMemoryScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
