// Code generated by mockery v2.15.0. DO NOT EDIT.

package yapscan

import (
	procio "github.com/fkie-cad/yapscan/procio"
	mock "github.com/stretchr/testify/mock"
)

// MockMemorySegmentFilterFunc is an autogenerated mock type for the MemorySegmentFilterFunc type
type MockMemorySegmentFilterFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: info
func (_m *MockMemorySegmentFilterFunc) Execute(info *procio.MemorySegmentInfo) bool {
	ret := _m.Called(info)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*procio.MemorySegmentInfo) bool); ok {
		r0 = rf(info)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewMockMemorySegmentFilterFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMemorySegmentFilterFunc creates a new instance of MockMemorySegmentFilterFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMemorySegmentFilterFunc(t mockConstructorTestingTNewMockMemorySegmentFilterFunc) *MockMemorySegmentFilterFunc {
	mock := &MockMemorySegmentFilterFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
